repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.0
  hooks:
  - id: black
    language_version: python3.9
    args: ["object_tracking_cli", "tests"]
- repo: https://github.com/jendrikseipp/vulture
  rev: v2.10
  hooks:
  - id: vulture
    args: ["object_tracking_cli", "tests", --min-confidence=90, --sort-by-size]

- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
    args: [--remove-all-unused-imports, --in-place]