video:
  desired_fps: 30
  output_width: 800

detection:
  conf: 0.5
  iou: 0.5

trackers:
  - Greedy Euclidean:
      max_missing_frames: 3
      cost_matrix_func:
        euclidean_cost_matrix:
      assignment_func:
        greedy_assignment: 
      motion_model_cls:
        MotionAgnosticModel:

  - Hungarian IOU:
      max_missing_frames: 3
      cost_matrix_func:
        iou_cost_matrix:
      assignment_func:
        hungarian_assignment:
          th: 0.9
      motion_model_cls:
        MotionAgnosticModel:
        


