video:
  desired_fps: 30.
  output_width: 800

detection:
  conf: 0.3
  iou: 0.7

trackers:
  - CentroidTracker:
      assignment_strategy: 'naive'
      max_missing_frames: 3
  
  - CentroidTracker:
      assignment_strategy: 'kd_tree'
      max_missing_frames: 3

