video:
  desired_fps: 30
  output_width: 800

detection:
  conf: 0.5
  iou: 0.5

trackers:
  - Tracker_1:
      max_missing_frames: 3
      cost_matrix_func:
        iou_cost_matrix:
      assignment_func:
        greedy_assignment: 
        


