video:
  desired_fps: 30
  output_width: 800

detection:
  conf: 0.5
  iou: 0.5

trackers:
  - Motion Agnostic:
      max_missing_frames: 10
      cost_matrix_func:
        iou_cost_matrix:
      assignment_func:
        hungarian_assignment:
          th: 0.9
      motion_model_cls:
        MotionAgnosticModel:

  - KFCentroidVelocityModel:
      max_missing_frames: 10
      cost_matrix_func:
        iou_cost_matrix:
      assignment_func:
        hungarian_assignment:
          th: 0.9
      motion_model_cls:
        KFCentroidVelocityModel:
        


