video:
  desired_fps: 30
  output_width: 800

detection:
  conf: 0.5
  iou: 0.5

trackers:
  - MotionAgnosticTracker:
      assignment_strategy: 'naive'
      cost: 'euclidean'
      max_missing_frames: 3
  
  - MotionAgnosticTracker:
      assignment_strategy: 'naive'
      cost: 'iou'
      max_missing_frames: 3


